Greeting.create!(greeting: 'Hello, Otto!')
Greeting.create!(greeting: 'Kedu, Otto!')
Greeting.create!(greeting: 'Bawoni, Otto!')
Greeting.create!(greeting: 'Yaya, Otto!')
Greeting.create!(greeting: 'Bwanji, Otto!')
